### ISSUE TITLE
[BUG] Running bitnami-docker-rabbitmq with docker-compose and access it using guest / guest

### ISSUE THREAD

**Issue by LybrialsGit** [bitnami/bitnami-docker-rabbitmq#114]
Im trying to use bitnami docker rabbitmq and orchestrate it with docker compose to use it for spring cloud bus to refresh configs.

The problem is that my services cannot authenticate with rabbitmq

**Steps to reproduce the issue:**

First: This is my docker-compose.yml

```
version: "3"

services:

  rabbitmq:
    image: bitnami/rabbitmq:3.8
    container_name: rabbitmq
    environment:
      RABBITMQ_USERNAME: guest
      RABBITMQ_PASSWORD: guest

  config-server:
    build:
      context: config-server
      dockerfile: Dockerfile
    container_name: config-server
    depends_on:
      - rabbitmq
    environment:
      RABBIT_MQ_HOST: "rabbitmq"
      RABBIT_MQ_PORT: "5672"
      RABBIT_MQ_URSER_NAME: "guest"
      RABBIT_MQ_URSER_PASSWORD: "guest"
    ports:
      - "8888:8888"

  eureka-server:
    build:
      context: eureka-server
      dockerfile: Dockerfile
    container_name: eureka-server
    depends_on:
      - rabbitmq
      - config-server
    environment:
      RABBIT_MQ_HOST: "rabbitmq"
      RABBIT_MQ_PORT: "5672"
      RABBIT_MQ_URSER_NAME: "guest"
      RABBIT_MQ_URSER_PASSWORD: "guest"
      CONFIG_HOST: "config-server"
      CONFIG_PORT: "8888"
    ports:
      - "8761:8761"
```

When I run it with `docker-compose up` I see that all the services are starting but they cannot connect. With each service I get the following error:

```
eureka-server    | 2020-03-30 07:57:43.200  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [rabbitmq:5672]
rabbitmq          | 2020-03-30 07:57:43.202 [info] <0.743.0> accepting AMQP connection <0.743.0> (172.20.0.7:42120 -> 172.20.0.2:5672)
rabbitmq          | 2020-03-30 07:57:43.209 [info] <0.743.0> Connection <0.743.0> (172.20.0.7:42120 -> 172.20.0.2:5672) has a client-provided name: rabbitConnectionFactory#2a1edad4:1
rabbitmq          | 2020-03-30 07:57:43.210 [error] <0.743.0> Error on AMQP connection <0.743.0> (172.20.0.7:42120 -> 172.20.0.2:5672, state: starting):
rabbitmq          | PLAIN login refused: user 'guest' can only connect via localhost
rabbitmq          | 2020-03-30 07:57:43.211 [info] <0.743.0> closing AMQP connection <0.743.0> (172.20.0.7:42120 -> 172.20.0.2:5672 - rabbitConnectionFactory#2a1edad4:1)
eureka-server    | 2020-03-30 07:57:43.212  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [rabbitmq:5672]
rabbitmq          | 2020-03-30 07:57:43.214 [info] <0.746.0> accepting AMQP connection <0.746.0> (172.20.0.7:42122 -> 172.20.0.2:5672)
eureka-server    | 2020-03-30 07:57:43.220  WARN 1 --- [172.20.0.2:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
rabbitmq          | 2020-03-30 07:57:43.231 [info] <0.746.0> Connection <0.746.0> (172.20.0.7:42122 -> 172.20.0.2:5672) has a client-provided name: rabbitConnectionFactory#2a1edad4:2
rabbitmq          | 2020-03-30 07:57:43.231 [error] <0.746.0> Error on AMQP connection <0.746.0> (172.20.0.7:42122 -> 172.20.0.2:5672, state: starting):
rabbitmq          | PLAIN login refused: user 'guest' can only connect via localhost
rabbitmq          | 2020-03-30 07:57:43.232 [info] <0.746.0> closing AMQP connection <0.746.0> (172.20.0.7:42122 -> 172.20.0.2:5672 - rabbitConnectionFactory#2a1edad4:2)
eureka-server    | 2020-03-30 07:57:43.238  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [rabbitmq:5672]
rabbitmq          | 2020-03-30 07:57:43.239 [info] <0.749.0> accepting AMQP connection <0.749.0> (172.20.0.7:42124 -> 172.20.0.2:5672)
eureka-server    | 2020-03-30 07:57:43.244  WARN 1 --- [172.20.0.2:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
rabbitmq          | 2020-03-30 07:57:43.260 [info] <0.749.0> Connection <0.749.0> (172.20.0.7:42124 -> 172.20.0.2:5672) has a client-provided name: rabbitConnectionFactory#2a1edad4:3
rabbitmq          | 2020-03-30 07:57:43.260 [error] <0.749.0> Error on AMQP connection <0.749.0> (172.20.0.7:42124 -> 172.20.0.2:5672, state: starting):
rabbitmq          | PLAIN login refused: user 'guest' can only connect via localhost
rabbitmq          | 2020-03-30 07:57:43.261 [info] <0.749.0> closing AMQP connection <0.749.0> (172.20.0.7:42124 -> 172.20.0.2:5672 - rabbitConnectionFactory#2a1edad4:3)
eureka-server    | 2020-03-30 07:57:43.262  WARN 1 --- [172.20.0.2:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
eureka-server     | 2020-03-30 07:57:43.287  INFO 1 --- [nio-8761-exec-2] c.n.e.registry.AbstractInstanceRegistry  : Registered instance USER-SERVICE/bab7f3610796:user-service:8000 with status UP (replication=false)
eureka-server    | 2020-03-30 07:57:43.350  INFO 1 --- [nfoReplicator-0] com.netflix.discovery.DiscoveryClient    : DiscoveryClient_USER-SERVICE/bab7f3610796:user-service:8000 - registration status: 204
eureka-server    | 2020-03-30 07:57:43.369  INFO 1 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'springCloudBus.anonymous.YnwiIZpPREqqSx7oH6jxgg.errors' has 1 subscriber(s).
eureka-server    | 2020-03-30 07:57:43.370  INFO 1 --- [           main] o.s.c.stream.binder.BinderErrorChannel   : Channel 'springCloudBus.anonymous.YnwiIZpPREqqSx7oH6jxgg.errors' has 2 subscriber(s).
eureka-server    | 2020-03-30 07:57:43.382  INFO 1 --- [           main] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [rabbitmq:5672]
rabbitmq          | 2020-03-30 07:57:43.389 [info] <0.753.0> accepting AMQP connection <0.753.0> (172.20.0.7:42126 -> 172.20.0.2:5672)
rabbitmq          | 2020-03-30 07:57:43.395 [info] <0.753.0> Connection <0.753.0> (172.20.0.7:42126 -> 172.20.0.2:5672) has a client-provided name: rabbitConnectionFactory#2a1edad4:4
rabbitmq          | 2020-03-30 07:57:43.395 [error] <0.753.0> Error on AMQP connection <0.753.0> (172.20.0.7:42126 -> 172.20.0.2:5672, state: starting):
rabbitmq          | PLAIN login refused: user 'guest' can only connect via localhost
rabbitmq          | 2020-03-30 07:57:43.396 [info] <0.753.0> closing AMQP connection <0.753.0> (172.20.0.7:42126 -> 172.20.0.2:5672 - rabbitConnectionFactory#2a1edad4:4)
eureka-server    | 2020-03-30 07:57:43.397  INFO 1 --- [           main] o.s.a.r.l.SimpleMessageListenerContainer : Broker not available; cannot force queue declarations during start: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
eureka-server    | 2020-03-30 07:57:43.411  WARN 1 --- [172.20.0.2:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
eureka-server    | 2020-03-30 07:57:43.455  INFO 1 --- [EqqSx7oH6jxgg-1] o.s.a.r.c.CachingConnectionFactory       : Attempting to connect to: [rabbitmq:5672]
rabbitmq          | 2020-03-30 07:57:43.456 [info] <0.756.0> accepting AMQP connection <0.756.0> (172.20.0.7:42128 -> 172.20.0.2:5672)
rabbitmq          | 2020-03-30 07:57:43.463 [info] <0.756.0> Connection <0.756.0> (172.20.0.7:42128 -> 172.20.0.2:5672) has a client-provided name: rabbitConnectionFactory#2a1edad4:5
rabbitmq          | 2020-03-30 07:57:43.463 [error] <0.756.0> Error on AMQP connection <0.756.0> (172.20.0.7:42128 -> 172.20.0.2:5672, state: starting):
rabbitmq          | PLAIN login refused: user 'guest' can only connect via localhost
rabbitmq          | 2020-03-30 07:57:43.464 [info] <0.756.0> closing AMQP connection <0.756.0> (172.20.0.7:42128 -> 172.20.0.2:5672 - rabbitConnectionFactory#2a1edad4:5)
eureka-server    | 2020-03-30 07:57:43.465  WARN 1 --- [172.20.0.2:5672] c.r.c.impl.ForgivingExceptionHandler     : An unexpected connection driver error occured (Exception message: Socket closed)
eureka-server    | 2020-03-30 07:57:43.481 ERROR 1 --- [EqqSx7oH6jxgg-1] o.s.a.r.l.SimpleMessageListenerContainer : Consumer received fatal exception on startup
eureka-server    |
eureka-server    | org.springframework.amqp.rabbit.listener.exception.FatalListenerStartupException: Authentication failure
eureka-server    |     at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:566) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1343) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1188) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at java.lang.Thread.run(Thread.java:748) [na:1.8.0_212]
eureka-server    | Caused by: org.springframework.amqp.AmqpAuthenticationException: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
eureka-server    |     at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:64) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:510) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:751) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:214) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceFactory.createConnection(ConnectionFactoryUtils.java:293) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:130) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:92) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:75) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:560) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     ... 3 common frames omitted
eureka-server    | Caused by: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
eureka-server    |     at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:364) ~[amqp-client-5.7.3.jar!/:5.7.3]
eureka-server    |     at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1115) ~[amqp-client-5.7.3.jar!/:5.7.3]
eureka-server    |     at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063) ~[amqp-client-5.7.3.jar!/:5.7.3]
eureka-server    |     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connect(AbstractConnectionFactory.java:526) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:473) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     ... 10 common frames omitted
eureka-server    |
eureka-server    | 2020-03-30 07:57:43.487 ERROR 1 --- [           main] o.s.cloud.stream.binding.BindingService  : Failed to create consumer binding; retrying in 30 seconds
eureka-server    |
eureka-server    | org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer:
eureka-server    |     at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:461) ~[spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:90) ~[spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:169) [spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:126) [spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:112) [spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) [spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:1.8.0_212]
eureka-server    |     at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) [spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:894) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:162) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.6.RELEASE.jar!/:2.2.6.RELEASE]
eureka-server    |     at de.fronetic.userservice.UserServiceApplication.main(UserServiceApplication.java:12) ~[classes!/:0.0.1-SNAPSHOT]
eureka-server    |     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_212]
eureka-server    |     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_212]
eureka-server    |     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_212]
eureka-server    |     at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_212]
eureka-server    |     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[app.jar:0.0.1-SNAPSHOT]
eureka-server    |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[app.jar:0.0.1-SNAPSHOT]
eureka-server    |     at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[app.jar:0.0.1-SNAPSHOT]
eureka-server    |     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[app.jar:0.0.1-SNAPSHOT]
eureka-server    | Caused by: org.springframework.amqp.AmqpIllegalStateException: Fatal exception on listener startup
eureka-server    |     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.waitForConsumersToStart(SimpleMessageListenerContainer.java:612) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer.doStart(SimpleMessageListenerContainer.java:573) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.AbstractMessageListenerContainer.start(AbstractMessageListenerContainer.java:1301) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.integration.amqp.inbound.AmqpInboundChannelAdapter.doStart(AmqpInboundChannelAdapter.java:167) ~[spring-integration-amqp-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:156) ~[spring-integration-core-5.2.5.RELEASE.jar!/:5.2.5.RELEASE]
eureka-server    |     at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:414) ~[spring-cloud-stream-3.0.3.RELEASE.jar!/:3.0.3.RELEASE]
eureka-server    |     ... 32 common frames omitted
eureka-server    | Caused by: org.springframework.amqp.rabbit.listener.exception.FatalListenerStartupException: Authentication failure
eureka-server    |     at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:566) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.initialize(SimpleMessageListenerContainer.java:1343) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.SimpleMessageListenerContainer$AsyncMessageProcessingConsumer.run(SimpleMessageListenerContainer.java:1188) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
eureka-server    | Caused by: org.springframework.amqp.AmqpAuthenticationException: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
eureka-server    |     at org.springframework.amqp.rabbit.support.RabbitExceptionTranslator.convertRabbitAccessException(RabbitExceptionTranslator.java:64) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:510) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createConnection(CachingConnectionFactory.java:751) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.createConnection(ConnectionFactoryUtils.java:214) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils$RabbitResourceFactory.createConnection(ConnectionFactoryUtils.java:293) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.doGetTransactionalResourceHolder(ConnectionFactoryUtils.java:130) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:92) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.ConnectionFactoryUtils.getTransactionalResourceHolder(ConnectionFactoryUtils.java:75) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.listener.BlockingQueueConsumer.start(BlockingQueueConsumer.java:560) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     ... 3 common frames omitted
eureka-server    | Caused by: com.rabbitmq.client.AuthenticationFailureException: ACCESS_REFUSED - Login was refused using authentication mechanism PLAIN. For details see the broker logfile.
eureka-server    |     at com.rabbitmq.client.impl.AMQConnection.start(AMQConnection.java:364) ~[amqp-client-5.7.3.jar!/:5.7.3]
eureka-server    |     at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1115) ~[amqp-client-5.7.3.jar!/:5.7.3]
eureka-server    |     at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1063) ~[amqp-client-5.7.3.jar!/:5.7.3]
eureka-server    |     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.connect(AbstractConnectionFactory.java:526) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     at org.springframework.amqp.rabbit.connection.AbstractConnectionFactory.createBareConnection(AbstractConnectionFactory.java:473) ~[spring-rabbit-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
eureka-server    |     ... 10 common frames omitted

```

So it is actually saying that I cannot use a `PLAIN login`?

**Version**

- Output of `docker version`:

```
$ docker version
Client: Docker Engine - Community
 Version:           19.03.8
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        afacb8b
 Built:             Wed Mar 11 01:23:10 2020
 OS/Arch:           windows/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.8
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       afacb8b
  Built:            Wed Mar 11 01:29:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683

```

- Output of `docker info`:

```
$ docker info
Client:
 Debug Mode: false

Server:
 Containers: 24
  Running: 0
  Paused: 0
  Stopped: 24
 Images: 256
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.943GiB
 Name: docker-desktop
 ID: VCFA:56W7:EYGP:QCCB:O2S6:YFJT:74ZJ:ED6C:ODSX:KISS:HH67:H4LK
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 37
  Goroutines: 53
  System Time: 2020-03-30T08:06:33.940290923Z
  EventsListeners: 3
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine

```

- Output of `docker-compose version` (if applicable):

```
$ docker-compose version
docker-compose version 1.25.4, build 8d51620a
docker-py version: 4.1.0
CPython version: 3.7.4
OpenSSL version: OpenSSL 1.1.1c  28 May 2019

```

**Comment by juan131** [comment]
Hi @LybrialsGit 

I couldn't reproduce the issue using the `docker-compose.yaml` below:

```yaml
version: '2'

services:
  rabbitmq:
    image: 'bitnami/rabbitmq:3.8'
    ports:
      - '4369:4369'
      - '5672:5672'
      - '25672:25672'
      - '15672:15672'
    environment:
      RABBITMQ_USERNAME: foo
      RABBITMQ_PASSWORD: bar
    volumes:
      - 'rabbitmq_data:/bitnami'

volumes:
  rabbitmq_data:
    driver: local
```

- I created the containers:

```console
$ docker-compose up -d
```
- Then I waited until RabbitMQ is up:

```console
$ docker-compose logs -f rabbitmq
(...)
rabbitmq_1  |  06:55:15.34 INFO  ==> ** RabbitMQ setup finished! **
rabbitmq_1  |  06:55:15.37 INFO  ==> ** Starting RabbitMQ **
```

- Then I opened Chrome and browsed to http://127.0.0.1:15672 where I set the credentials:

![Screenshot 2020-03-31 at 09 11 38](https://user-images.githubusercontent.com/6740773/77997406-a5c48b80-732f-11ea-9869-cbb3624277f4.png)

- As you can see, I could access the admin panel:

![Screenshot 2020-03-31 at 09 12 06](https://user-images.githubusercontent.com/6740773/77997466-c12f9680-732f-11ea-9ce3-86dce7c87dc7.png)


Please note that "guest" user can only be used through localhost, see https://www.rabbitmq.com/access-control.html#loopback-users

**Comment by LybrialsGit** [comment]
localhost -> this
