### ISSUE TITLE
Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq

### ISSUE THREAD

**Issue by valerianpereira** [bitnami/bitnami-docker-rabbitmq#85]
**The rabbitmq container does not spin up correctly and fails with an error as `Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq`**

**Steps to reproduce the issue:**

1. docker run -d -p 15672:15672 -p 5672:5672 --name rabbitmq-server bitnami/rabbitmq:latest
2. docker logs rabbitmq-server
3. `Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq`

**Checking the logs gives the following error**
```
[root@server-name-1 ~]# docker logs rabbitmq-server

Welcome to the Bitnami rabbitmq container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues

nami    INFO  Initializing rabbitmq
rabbitm INFO  Creating RabbitMQ System User...
rabbitm INFO  Setting RabbitMQ environment...
rabbitm INFO  Setting Erlang cookie...
rabbitm INFO  Managing RabbitMQ plugins...
rabbitm INFO  Configuring RabbitMQ permissions...
rabbitm INFO  Starting RabbitMQ node rabbit@localhost...
Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
```

**Version**

- Output of `docker version`:

```
[root@server-name-1 ~]# docker version
Client:
 Version:	18.03.0-ce
 API version:	1.37
 Go version:	go1.9.4
 Git commit:	0520e24
 Built:	Wed Mar 21 23:09:15 2018
 OS/Arch:	linux/amd64
 Experimental:	false
 Orchestrator:	swarm

Server:
 Engine:
  Version:	18.03.0-ce
  API version:	1.37 (minimum version 1.12)
  Go version:	go1.9.4
  Git commit:	0520e24
  Built:	Wed Mar 21 23:13:03 2018
  OS/Arch:	linux/amd64
  Experimental:	false
```

- Output of `docker info`:

```
[root@server-name-1 ~]# docker info
Containers: 1
 Running: 0
 Paused: 0
 Stopped: 1
Images: 1
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 3.10.0-862.2.3.el7.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 15.51GiB
Name: odp-de-jobs-1
ID: S4Q7:ETH6:P6H6:GORN:G4HC:C4EL:OWNS:MUPF:JDU4:N5U7:HHT6:4GQC
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

Please advice.

**Additional environment details (AWS, VirtualBox, Docker for MAC, physical, etc.):**

**Comment by andresbono** [comment]
Hi @valerianpereira, unfortunately we can't reproduce the issue. Could you please execute the command with an extra environment variable for debugging purposes?

```
docker run -e NAMI_LOG_LEVEL=trace -p 15672:15672 -p 5672:5672 --name rabbitmq-server bitnami/rabbitmq:latest
```

That way you may find more information about the issue.

**Comment by ankyjk** [comment]
@andresbono  Below is the Error Stack trace which we are getting

```docker run -e NAMI_LOG_LEVEL=trace -p 15672:15672 -p 5672:5672 --name rabbitmq-server bitnami/rabbitmq:latest

Welcome to the Bitnami rabbitmq container
Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-rabbitmq
Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-rabbitmq/issues

nami    INFO  Initializing rabbitmq
rabbitm INFO  Creating RabbitMQ System User...
rabbitm INFO  Setting RabbitMQ environment...
rabbitm TRACE [prepareDataToPersist] Preparing /opt/bitnami/rabbitmq/conf to persist in /bitnami/rabbitmq/conf
rabbitm TRACE [prepareDataToPersist] Preparing /opt/bitnami/rabbitmq/var/lib/rabbitmq to persist in /bitnami/rabbitmq/var/lib/rabbitmq
rabbitm TRACE [prepareDataToPersist] Preparing /opt/bitnami/rabbitmq/.rabbitmq to persist in /bitnami/rabbitmq/.rabbitmq
rabbitm INFO  Setting Erlang cookie...
rabbitm INFO  Managing RabbitMQ plugins...
rabbitm TRACE Running: rabbitmq-plugins [ 'enable', 'rabbitmq_management' ] { env:
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmq-plugins enable,rabbitmq_management
rabbitm INFO  Configuring RabbitMQ permissions...
rabbitm INFO  Starting RabbitMQ node rabbit@localhost...
rabbitm TRACE Running: rabbitmqctl node_health_check { retrieveStdStreams: true,
  env:
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmqctl node_health_check
rabbitm TRACE [runProgram] Executing: null rabbitmq-server
rabbitm TRACE Running: rabbitmqctl node_health_check { retrieveStdStreams: true,
  .
  .
  .
  .
  env:
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmqctl node_health_check
rabbitm TRACE Last log entries:
2018-12-27 07:04:16.153 [info] <0.4516.0> accepting AMQP connection <0.4516.0> (172.20.10.17:57177 -> 172.17.0.2:5672)
2018-12-27 07:04:16.154 [error] <0.4516.0> Error on AMQP connection <0.4516.0> (172.20.10.17:57177 -> 172.17.0.2:5672, state: starting):
PLAIN login refused: user 'dataengine' - invalid credentials
2018-12-27 07:04:16.154 [info] <0.4516.0> closing AMQP connection <0.4516.0> (172.20.10.17:57177 -> 172.17.0.2:5672)
2018-12-27 07:04:16.168 [info] <0.4520.0> accepting AMQP connection <0.4520.0> (172.20.10.17:57178 -> 172.17.0.2:5672)
2018-12-27 07:04:16.169 [error] <0.4520.0> Error on AMQP connection <0.4520.0> (172.20.10.17:57178 -> 172.17.0.2:5672, state: starting):
PLAIN login refused: user 'dataengine' - invalid credentials
2018-12-27 07:04:16.169 [info] <0.4520.0> closing AMQP connection <0.4520.0> (172.20.10.17:57178 -> 172.17.0.2:5672)
2018-12-27 07:04:17.014 [warning]  lager_file_backend dropped 6 messages in the last second that exceeded the limit of 50 messages/sec

Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
nami    TRACE Error: Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
    at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:162:15)
    at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
    at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.rabbitmq/main.js:69:10)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)```

**Comment by andresbono** [comment]
These are the last 10 lines of the log file:

```
2018-12-27 07:04:16.153 [info] <0.4516.0> accepting AMQP connection <0.4516.0> (172.20.10.17:57177 -> 172.17.0.2:5672)
2018-12-27 07:04:16.154 [error] <0.4516.0> Error on AMQP connection <0.4516.0> (172.20.10.17:57177 -> 172.17.0.2:5672, state: starting):
PLAIN login refused: user 'dataengine' - invalid credentials
2018-12-27 07:04:16.154 [info] <0.4516.0> closing AMQP connection <0.4516.0> (172.20.10.17:57177 -> 172.17.0.2:5672)
2018-12-27 07:04:16.168 [info] <0.4520.0> accepting AMQP connection <0.4520.0> (172.20.10.17:57178 -> 172.17.0.2:5672)
2018-12-27 07:04:16.169 [error] <0.4520.0> Error on AMQP connection <0.4520.0> (172.20.10.17:57178 -> 172.17.0.2:5672, state: starting):
PLAIN login refused: user 'dataengine' - invalid credentials
2018-12-27 07:04:16.169 [info] <0.4520.0> closing AMQP connection <0.4520.0> (172.20.10.17:57178 -> 172.17.0.2:5672)
2018-12-27 07:04:17.014 [warning]  lager_file_backend dropped 6 messages in the last second that exceeded the limit of 50 messages/sec
```

It is difficult to determine the root cause of the issue but it seems that you have clients making requests before the server is completely initialized.

Could you try to run the container without exposing the ports?

```
docker run -e NAMI_LOG_LEVEL=trace --name rabbitmq-server bitnami/rabbitmq:latest
```

Does it make a difference?

**Comment by ankyjk** [comment]
Tried that, but does not make any difference,
Again got the same issue

```  env:
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmqctl node_health_check
rabbitm TRACE Last log entries:
2018-12-28 04:27:36.777 [info] <0.212.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@localhost
2018-12-28 04:27:36.780 [info] <0.212.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@localhost
2018-12-28 04:27:36.821 [info] <0.547.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2018-12-28 04:27:36.821 [info] <0.653.0> Statistics database started.
2018-12-28 04:27:36.822 [notice] <0.104.0> Changed loghwm of /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@localhost.log to 50
2018-12-28 04:27:36.946 [info] <0.7.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_management_agent
 * rabbitmq_web_dispatch

Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
nami    TRACE Error: Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
    at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:162:15)
    at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
    at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.rabbitmq/main.js:69:10)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)```

**Comment by andresbono** [comment]
I'm running out of ideas 🤔

Could you try with a specific image version?

```
docker run -e NAMI_LOG_LEVEL=trace --name rabbitmq-server bitnami/rabbitmq@sha256:74802825104ee470464b5b59e8699e0b05f29412b3224cb0bea2507533133fde
```

**Comment by ankyjk** [comment]
I tried the above docker run command , Still got the Error
``` env:
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmqctl node_health_check
rabbitm TRACE Last log entries:
2019-01-10 06:36:25.741 [info] <0.213.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@localhost
2019-01-10 06:36:25.743 [info] <0.213.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@localhost
2019-01-10 06:36:25.765 [info] <0.538.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2019-01-10 06:36:25.765 [info] <0.644.0> Statistics database started.
2019-01-10 06:36:25.766 [notice] <0.105.0> Changed loghwm of /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@localhost.log to 50
2019-01-10 06:36:25.831 [info] <0.8.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent

Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
nami    TRACE Error: Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
    at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:162:15)
    at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
    at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.rabbitmq/main.js:69:10)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)```

**Comment by AleksandrShepelev** [comment]
+1, same issue

**Comment by andresbono** [comment]
Hi @AleksandrShepelev, can you tell us what is the environment of your Docker host? Did you try the commands suggested above? Did any of them help to find the cause of the issue?

**Comment by valerianpereira** [comment]
Well, @ankyjk was running out of space on his server which caused this trouble. The service is up and running now. Thanks everyone.

**Comment by carrodher** [comment]
Thanks, we're glad the issue was solved.
@AleksandrShepelev do you still have this issue?

**Comment by tauinger-de** [comment]
Sorry, must reopen this issue. Disk space is not an issue, a `df . -h` reports 5.7G available.

After executing
```
docker run -e NAMI_LOG_LEVEL=trace --name rabbitmq-server bitnami/rabbitmq@sha256:74802825104ee470464b5b59e8699e0b05f29412b3224cb0bea2507533133fde
```
I get the following output:
```
nami    INFO  Initializing rabbitmq
rabbitm INFO  Creating RabbitMQ System User...
rabbitm INFO  Setting RabbitMQ environment...
rabbitm TRACE [prepareDataToPersist] Preparing /opt/bitnami/rabbitmq/conf to persist in /bitnami/rabbitmq/conf
rabbitm TRACE [prepareDataToPersist] Preparing /opt/bitnami/rabbitmq/var/lib/rabbitmq to persist in /bitnami/rabbitmq/var/lib/rabbitmq
rabbitm TRACE [prepareDataToPersist] Preparing /opt/bitnami/rabbitmq/.rabbitmq to persist in /bitnami/rabbitmq/.rabbitmq
rabbitm INFO  Setting Erlang cookie...
rabbitm INFO  Managing RabbitMQ plugins...
rabbitm TRACE Running: rabbitmq-plugins [ 'enable', 'rabbitmq_management' ] { env: 
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmq-plugins enable,rabbitmq_management
rabbitm INFO  Configuring RabbitMQ permissions...
rabbitm INFO  Starting RabbitMQ node rabbit@localhost...
rabbitm TRACE Running: rabbitmqctl node_health_check { retrieveStdStreams: true,
  env: 
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmqctl node_health_check
rabbitm TRACE [runProgram] Executing: null rabbitmq-server

...

rabbitm TRACE Running: rabbitmqctl node_health_check { retrieveStdStreams: true,
  env: 
   { PATH: '/opt/bitnami/rabbitmq/bin:/opt/bitnami/erlang/bin:/opt/bitnami/erlang/bin:/opt/bitnami/rabbitmq/bin:/opt/bitnami/rabbitmq/sbin:/opt/bitnami/nami/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' } }
rabbitm TRACE [runProgram] Executing: rabbitmqctl node_health_check
rabbitm TRACE Last log entries:
2019-05-17 08:08:56.095 [info] <0.213.0> Setting up a table for connection tracking on this node: tracked_connection_on_node_rabbit@localhost
2019-05-17 08:08:56.100 [info] <0.213.0> Setting up a table for per-vhost connection counting on this node: tracked_connection_per_vhost_on_node_rabbit@localhost
2019-05-17 08:08:56.131 [info] <0.550.0> Management plugin: HTTP (non-TLS) listener started on port 15672
2019-05-17 08:08:56.131 [info] <0.656.0> Statistics database started.
2019-05-17 08:08:56.132 [notice] <0.105.0> Changed loghwm of /opt/bitnami/rabbitmq/var/log/rabbitmq/rabbit@localhost.log to 50
2019-05-17 08:08:56.197 [info] <0.8.0> Server startup complete; 3 plugins started.
 * rabbitmq_management
 * rabbitmq_web_dispatch
 * rabbitmq_management_agent

nami    TRACE Error: Error executing 'postInstallation': Unable to start com.bitnami.rabbitmq
    at Service._execServiceCommand (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:162:15)
    at Service._start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:348:12)
    at Service.start (/opt/bitnami/nami/node_modules/nami-core/lib/components/service.js:376:30)
    at Service.$app.postInstallation (/.nami/components/com.bitnami.rabbitmq/main.js:69:10)
    at Service.runStep (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:159:12)
    at _.each.step (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:32)
    at r (/opt/bitnami/nami/node_modules/lodash/index.js:5:348)
    at Function.sf (/opt/bitnami/nami/node_modules/lodash/index.js:78:256)
    at Service.install (/opt/bitnami/nami/node_modules/nami-core/lib/components/component.js:236:7)
    at Manager.initializePackage (/opt/bitnami/nami/node_modules/nami-core/lib/manager.js:284:11)

```

**Comment by jordiJIG** [comment]
+ 1, same issue here

**Comment by tauinger-de** [comment]
PS:
```
uname -a
Linux NUXY 4.15.0-50-generic #54-Ubuntu SMP Mon May 6 18:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by andresbono** [comment]
Hi @jordiJIG, @tauinger-de, we tried again and we still can't reproduce the issue.

We will be moving the configuration logic of RabbitMQ from nami to bash, so hopefully, we will get this issue solved.

We are reopening the issue.

**Comment by jordiJIG** [comment]
Hi,

In my case, I had 2GB of free space and that's why I thought it was not a matter of space. As soon as I released 6Gb it worked without problem...

Thank you!

**Comment by tauinger-de** [comment]
Me too, I moved from around 5GB of free space to 26GB and now Rabbitmq keeps running.

@andresbono Have you tried reproducing on a filesystem with "low" disk space?

**Comment by tauinger-de** [comment]
![Screenshot from 2019-05-21 07-58-26](https://user-images.githubusercontent.com/45622761/58071936-6de0a980-7b9e-11e9-8e69-1a59ec2c22de.png)

Do you think the "16GB low watermark" detail might have something to do with it?

**Comment by andresbono** [comment]
It seems that is the issue @tauinger-de, jordiJIG.

RabbitMQ will not run if the free space is below the "low watermark": https://www.rabbitmq.com/disk-alarms.html#configure. In the container, the value is set relative to the amount of RAM that you have in your machine. So if you have 16GB of RAM, you will need, at least, that 16 GB of free disk space.

**Comment by tauinger-de** [comment]
That seems a bit oversized to me, given that the default value seems to be 50MB according to the link given.

Anyways I regard it as a bug that it's so difficult to trace down the root cause of the failing server

**Comment by andresbono** [comment]
@tauinger-de, that's the value recommended for production environments: https://www.rabbitmq.com/production-checklist.html#resource-limits-disk-space.

In any case, you can change the value by using the `RABBITMQ_DISK_FREE_LIMIT` env-var as explained in the [README.md](https://github.com/bitnami/bitnami-docker-rabbitmq#user-content-configuration).

You can set it to a fixed value or relative to memory:

```
RABBITMQ_DISK_FREE_LIMIT=1000000000
RABBITMQ_DISK_FREE_LIMIT='{mem_relative, 0.5}'
```

**Comment by tauinger-de** [comment]
Cool, thanks. How do you want to improve error reporting / logging on this issue?

**Comment by andresbono** [comment]
@tauinger-de, as it is an error reported by the application itself, there is not that much we can do to improve it.

**Comment by ajcann** [comment]
Just wanted to mention, for those searching for a solution like me, that we were experiencing this issue during Jenkins CI builds in kubernetes pods which had no memory limit/requests set. The underlying compute node's working disk space was being passed through as the disk size and the available memory was much higher than parity. Setting RABBITMQ_DISK_FREE_LIMIT to something appropriately  small solves the issue for us.

**Comment by andresbono** [comment]
Nice @ajcann, it's good to know that setting a proper value to the env var solves the issue for you too.
